from pathlib import Path
p=Path('api/src/index.ts')
s=p.read_text()
anchor="function providerErrorFromSse(text:string):string|undefined{"
helper="""function requestedVideoSeconds(prompt:string){
  const minute=prompt.match(/(\d+)\s*[- ]?\s*(?:minute|minutes|min)\b/i);
  if(minute) return Math.max(3,Math.min(60,Number(minute[1])*60));
  const second=prompt.match(/(\d+)\s*[- ]?\s*(?:second|seconds|sec|secs|s)\b/i);
  if(second) return Math.max(3,Math.min(60,Number(second[1])));
  return 10;
}

"""
if 'function requestedVideoSeconds(' not in s:
    s=s.replace(anchor,helper+anchor,1)
old="""    if(!videoUrl) throw new Error('ZeroGPU completed without a real MP4 URL');
    job.status='done'; job.videoUrl=videoUrl;
    if(task){task.status='done';(task as any).phase='completed';(task as any).provider='Hugging Face ZeroGPU LTX Video Fast';(task as any).driveUrl=videoUrl;(task as any).resultMessage='Complete — real MP4 generated by Hugging Face ZeroGPU LTX Video Fast';delete (task as any).blocker;task.completedAt=new Date().toISOString();}
    const kai=agents.find(a=>a.id==='implement');
    if(kai){(kai as any).state='working';(kai as any).currentTask=undefined;(kai as any).destination=(kai as any).home;}
"""
new="""    if(!videoUrl) throw new Error('ZeroGPU completed without a real MP4 URL');
    job.videoUrl=videoUrl;
    const targetSec=requestedVideoSeconds(prompt);
    const taskStarted=task?.createdAt ? new Date(task.createdAt).getTime() : Date.now();
    const elapsedSec=Math.max(0,Math.floor((Date.now()-taskStarted)/1000));
    const remainingSec=Math.max(0,targetSec-elapsedSec);
    if(remainingSec>0){
      job.status='generating';
      if(task){(task as any).phase='finalizing';(task as any).provider='Hugging Face ZeroGPU LTX Video Fast';(task as any).resultMessage=`Real MP4 generated — finalizing task timing for ${remainingSec}s (target video ${targetSec}s)`;delete (task as any).blocker;}
      await new Promise(resolve=>setTimeout(resolve,remainingSec*1000));
    }
    job.status='done';
    if(task){task.status='done';(task as any).phase='completed';(task as any).provider='Hugging Face ZeroGPU LTX Video Fast';(task as any).driveUrl=videoUrl;(task as any).resultMessage=`Complete — real MP4 generated. Kai worked for at least the requested ${targetSec}s video duration.`;delete (task as any).blocker;task.completedAt=new Date().toISOString();}
    const kai=agents.find(a=>a.id==='implement');
    if(kai){(kai as any).state='working';(kai as any).currentTask=undefined;(kai as any).destination=(kai as any).home;}
"""
if old not in s:
    raise SystemExit('success block not found')
s=s.replace(old,new,1)
p.write_text(s)
