from pathlib import Path
p=Path('api/src/index.ts')
s=p.read_text()
old="""    if(task){task.status='done';(task as any).phase='completed';(task as any).provider='Hugging Face ZeroGPU LTX Video Fast';(task as any).driveUrl=videoUrl;(task as any).resultMessage='Complete — real MP4 generated by Hugging Face ZeroGPU LTX Video Fast';delete (task as any).blocker;task.completedAt=new Date().toISOString();}
"""
new="""    if(task){task.status='done';(task as any).phase='completed';(task as any).provider='Hugging Face ZeroGPU LTX Video Fast';(task as any).driveUrl=videoUrl;(task as any).resultMessage='Complete — real MP4 generated by Hugging Face ZeroGPU LTX Video Fast';delete (task as any).blocker;task.completedAt=new Date().toISOString();}
    const kai=agents.find(a=>a.id==='implement');
    if(kai){(kai as any).state='working';(kai as any).currentTask=undefined;(kai as any).destination=(kai as any).home;}
"""
if old not in s:
    raise SystemExit('Kai success block not found')
s=s.replace(old,new,1)
p.write_text(s)
